# The name of the plugin (lowercase, no spaces)
name = "hello"

# A list of paths to WASM modules in the plugin (this can be used to group
# plugins together in a rudimentary way until we implement dependencies).
modules = []

# Plugins required by this plugin (currently unsupported, keep this empty)
dependencies = []

#assets = ["common/items/weapons/tool/paddle.ron", "voxygen/voxel/weapon/tool/paddle.vox", "voxygen/voxel/biped_weapon_manifest.ron", "voxygen/voxel/item_drop_manifest.ron", "voxygen/item_image_manifest.ron" ]
